name: hidra

channels:
  - defaults

dependencies:
  - python=3.7.16
  - tensorflow=2.4
  - scikit-learn=0.24.2
  - pandas=1.1.5
  - openpyxl==3.0.9
  - pip
  - pip:
    - git+https://github.com/ECP-CANDLE/candle_lib@develop
