name: hidra

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.11.7
  - tensorflow=2.14.0
  - scikit-learn=1.3.0
  - pandas=2.1.4
  - openpyxl=3.0.10
  - pip
  - pip:
    - git+https://github.com/ECP-CANDLE/candle_lib@develop
